# Taufiq July Kurniawan_Posttest 4 dan Posttest 7
# 2009106138

##### Import Library

In [141]:
import tensorflow as tf

##### Tensor Nilai Random

In [142]:
random_tensor = tf.random.normal([5,5])
random_tensor.numpy()

array([[-1.9871184 ,  2.331272  ,  0.1063799 , -0.87107515,  0.7004276 ],
       [ 0.9274295 , -0.2597045 ,  1.779798  , -0.7734136 , -0.82087314],
       [-0.1354295 ,  0.12380375,  0.37303653,  1.4451019 , -0.5829035 ],
       [ 1.7886226 , -0.5669783 ,  0.37228477,  1.0592332 ,  0.21335576],
       [ 0.34702832,  0.05337666, -1.4243888 ,  1.0036482 ,  0.8454301 ]],
      dtype=float32)

##### Tensor Bilangan Prima

In [147]:
bilangan = [[1,2,3,5,7], [11,13,17,19,23], [29, 31, 37, 41, 43],[47, 53, 59, 61, 67],[71, 73, 79, 83, 89]]
prime_tensor = tf.convert_to_tensor(bilangan, dtype= tf.float32)
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.,  2.,  3.,  5.,  7.],
       [11., 13., 17., 19., 23.],
       [29., 31., 37., 41., 43.],
       [47., 53., 59., 61., 67.],
       [71., 73., 79., 83., 89.]], dtype=float32)>

##### Dimensi Nilai Random dan Bilangan Prima

In [148]:
dimensi = tf.constant(random_tensor)
dimensi2 =tf.constant(prime_tensor)
print(dimensi.shape, dimensi2.shape)
print(dimensi.get_shape(), dimensi2.get_shape())
print(tf.shape(dimensi), tf.shape(dimensi2))

(5, 5) (5, 5)
(5, 5) (5, 5)
tf.Tensor([5 5], shape=(2,), dtype=int32) tf.Tensor([5 5], shape=(2,), dtype=int32)


##### Perhitungan Aritmatika Nilai Random dan Bilangan Prima

In [149]:
penjumlahan = tf.add(random_tensor, prime_tensor)
pengurangan = tf.subtract(random_tensor, prime_tensor)
perkalian = tf.multiply(random_tensor, prime_tensor)
pembagian = tf.divide(random_tensor, prime_tensor)
logaritma = tf.math.log(random_tensor, prime_tensor)
pangkat = tf.pow(random_tensor, prime_tensor)

print("Hasil dari Penjumlahan : ", penjumlahan, "\n")
print("Hasil dari Pengurangan : ", pengurangan, "\n")
print("Hasil dari Perkalian : ", perkalian, "\n")
print("Hasil dari Pembagian : ", pembagian, "\n")
print("Hasil dari Logaritma : ", logaritma, "\n")
print("Hasil dari Pangkat : ", pangkat, "\n")

Hasil dari Penjumlahan :  tf.Tensor(
[[-0.98711836  4.331272    3.10638     4.128925    7.7004275 ]
 [11.927429   12.740295   18.779799   18.226587   22.179127  ]
 [28.86457    31.123804   37.373035   42.445103   42.417095  ]
 [48.788624   52.43302    59.372284   62.059235   67.213356  ]
 [71.34703    73.053375   77.575615   84.00365    89.84543   ]], shape=(5, 5), dtype=float32) 

Hasil dari Pengurangan :  tf.Tensor(
[[ -2.9871182   0.3312719  -2.89362    -5.871075   -6.2995725]
 [-10.072571  -13.259705  -15.2202015 -19.773413  -23.820873 ]
 [-29.13543   -30.876196  -36.626965  -39.554897  -43.582905 ]
 [-45.211376  -53.56698   -58.627716  -59.940765  -66.786644 ]
 [-70.65297   -72.946625  -80.424385  -81.99635   -88.15457  ]], shape=(5, 5), dtype=float32) 

Hasil dari Perkalian :  tf.Tensor(
[[  -1.9871184    4.662544     0.3191397   -4.355376     4.902993 ]
 [  10.201724    -3.3761585   30.256567   -14.694859   -18.880083 ]
 [  -3.9274554    3.8379161   13.802352    59.249176   -25.

##### Nilai Max dan Min

##### Nilai Random

In [150]:
print("input tensor:",random_tensor.numpy())
maximum = tf.argmax(random_tensor, axis=0)
minimum = tf.argmin(random_tensor, axis=1)
print("Nilai Maksimum :",maximum.numpy())
print("Nilai Minimum :",minimum.numpy())

input tensor: [[-1.9871184   2.331272    0.1063799  -0.87107515  0.7004276 ]
 [ 0.9274295  -0.2597045   1.779798   -0.7734136  -0.82087314]
 [-0.1354295   0.12380375  0.37303653  1.4451019  -0.5829035 ]
 [ 1.7886226  -0.5669783   0.37228477  1.0592332   0.21335576]
 [ 0.34702832  0.05337666 -1.4243888   1.0036482   0.8454301 ]]
Nilai Maksimum : [3 0 1 2 4]
Nilai Minimum : [0 4 4 1 2]


##### Nilai bilangan prima

In [151]:
print("input tensor:",prime_tensor.numpy())
max = tf.argmax(prime_tensor, axis=0)
min = tf.argmin(prime_tensor, axis=1)
print("Nilai Maksimum :",max.numpy())
print("Nilai Minimum :",min.numpy())

input tensor: [[ 1.  2.  3.  5.  7.]
 [11. 13. 17. 19. 23.]
 [29. 31. 37. 41. 43.]
 [47. 53. 59. 61. 67.]
 [71. 73. 79. 83. 89.]]
Nilai Maksimum : [4 4 4 4 4]
Nilai Minimum : [0 0 0 0 0]


##### Penggabungan Variabel random dan prime

In [152]:
penggabungan = tf.stack([random_tensor, prime_tensor],axis=0)
print("Sebelum digabung : ",random_tensor.shape, prime_tensor.shape)
print("Setelah digabung :",penggabungan.shape)

Sebelum digabung :  (5, 5) (5, 5)
Setelah digabung : (2, 5, 5)


##### Sorting variabel Random

In [153]:
print("input tensor:",random_tensor.numpy())
random_sort = tf.sort(random_tensor, direction="DESCENDING")
print("Sorting Data Random Tensor:",random_sort.numpy())

input tensor: [[-1.9871184   2.331272    0.1063799  -0.87107515  0.7004276 ]
 [ 0.9274295  -0.2597045   1.779798   -0.7734136  -0.82087314]
 [-0.1354295   0.12380375  0.37303653  1.4451019  -0.5829035 ]
 [ 1.7886226  -0.5669783   0.37228477  1.0592332   0.21335576]
 [ 0.34702832  0.05337666 -1.4243888   1.0036482   0.8454301 ]]
Sorting Data Random Tensor: [[ 2.331272    0.7004276   0.1063799  -0.87107515 -1.9871184 ]
 [ 1.779798    0.9274295  -0.2597045  -0.7734136  -0.82087314]
 [ 1.4451019   0.37303653  0.12380375 -0.1354295  -0.5829035 ]
 [ 1.7886226   1.0592332   0.37228477  0.21335576 -0.5669783 ]
 [ 1.0036482   0.8454301   0.34702832  0.05337666 -1.4243888 ]]


##### sorting variabel Prime

In [154]:
print("input tensor:",prime_tensor.numpy())
prime_sort = tf.sort(prime_tensor, direction="DESCENDING")
print("Sorting Data Prime Tensor :",prime_sort.numpy())

input tensor: [[ 1.  2.  3.  5.  7.]
 [11. 13. 17. 19. 23.]
 [29. 31. 37. 41. 43.]
 [47. 53. 59. 61. 67.]
 [71. 73. 79. 83. 89.]]
Sorting Data Prime Tensor : [[ 7.  5.  3.  2.  1.]
 [23. 19. 17. 13. 11.]
 [43. 41. 37. 31. 29.]
 [67. 61. 59. 53. 47.]
 [89. 83. 79. 73. 71.]]
